#cloud-config
ssh_authorized_keys:
  - "${user_pubkey}"
coreos:
  locksmith:
  update:
    reboot-strategy: "${reboot_strategy}"
  units:
    - name: set-timezone.service
      enable: true
      content: |
        [Unit]
        Description=Set the time zone
        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone UTC
        RemainAfterExit=yes
        Type=oneshot
        [Install]
        WantedBy=multi-user.target
    - name: networkd-restart.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Restart systemd-networkd to be sure we are using correct network settings
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/bash -c 'systemctl restart systemd-networkd'
write_files:
  - path: /etc/kubernetes/azure.json
    content: ${azure_config}
    permissions: 0644
    owner: root
    encoding: b64
  - path: /etc/vpm/config.yaml
    permissions: 0644
    owner: root
    encoding: b64
    content: ${vp_manager_config}
  - path: /etc/hosts
    content: ${hosts_context}
    permissions: 0644
    owner: root
    encoding: b64
  - path: /etc/systemd/chronyd.conf
    permissions: 0420
    owner: root
    content: |
      pool ${ntp_servers} iburst
      driftfile /var/lib/chrony/drift
      makestep 0.1 3
      rtcsync